# Generated by Django 4.1.2 on 2022-11-03 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='data_measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-10-23T16:45:51.091212Z', verbose_name='Дата измерения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=20, verbose_name='Температура при измерении'),
        ),
    ]
