# Generated by Django 4.1.2 on 2022-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_measurement_data_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ManyToManyField(related_name='sensors', to='measurement.sensor'),
        ),
    ]
